// Generated by scripts/inventory/news.mjs from the Phase 1 crawl. Do not edit by hand.
// The 4 WordPress news posts, verbatim, as Portable Text. Sanity holds news once imported
// (scripts/import-content.ts); until then the site reads this list.
// Images already missing on the live site were not migrated:
//   thank-you-for-paying-it-forward: https://painmgmtgroup.com/wp-content/uploads/2018/01/Screenshot.png (404 on the live site)
//   thank-you-for-paying-it-forward: https://painmgmtgroup.com/wp-content/uploads/2018/01/Screenshot2.png (404 on the live site)

export type LegacyImage = {
  _type: "image";
  _key: string;
  src: string;
  alt: string;
  width: number;
  height: number;
};
export type LegacyBlock = {
  _type: "block";
  _key: string;
  style: string;
  markDefs: { _type: "link"; _key: string; href: string }[];
  children: { _type: "span"; _key: string; text: string; marks: string[] }[];
};
export type LegacyNewsPost = {
  slug: string;
  title: string;
  date: string;
  body: (LegacyBlock | LegacyImage)[];
};

export const legacyNewsBodies: LegacyNewsPost[] = [
 {
  "slug": "pmg-helping-in-houston",
  "title": "PMG Helping In Houston",
  "date": "2017-12-07",
  "body": [
   {
    "_type": "block",
    "_key": "k1",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k0",
      "text": "Earlier in November, PMG sent a team of internal employees to help with Hurricane Harvey relief in Houston, Texas.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k3",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2",
      "text": "It was an amazing time serving together, and the experience definitely instilled a deeper sense of gratitude for the things we often take for granted.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k8",
    "style": "normal",
    "markDefs": [
     {
      "_type": "link",
      "_key": "k5",
      "href": "https://www.hands.org/"
     }
    ],
    "children": [
     {
      "_type": "span",
      "_key": "k4",
      "text": "Our team volunteered with a non-profit called ",
      "marks": []
     },
     {
      "_type": "span",
      "_key": "k6",
      "text": "All Hands & Hearts",
      "marks": [
       "k5"
      ]
     },
     {
      "_type": "span",
      "_key": "k7",
      "text": ". All Hands & Hearts commits to staying two full years on the ground cleaning, sanitizing, and rebuilding locations impacted by natural disasters around the world. We would highly recommend checking out opportunities with them if you are ever looking for an organization to volunteer with.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "ka",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k9",
      "text": "Our group of 8 worked with two All Hands team leaders at an apartment complex that experienced 10 feet of flooding. Our volunteer coordinator told us the landlord was rescuing people on an air mattress. These units were in bad shape, and sadly enough there are still families living in some of them who have no place else to go. We spent our time primarily tearing down ceilings, flooring, and walls, removing nails, and cleaning up insulation.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "kc",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "kb",
      "text": "It was a privilege to spend a few days outside our normal routines to help those impacted by Hurricane Harvey. There’s still much work to be done! Many families will experience a different holiday season this year, and as we approach a season of gratitude and giving, we encourage you all to consider how you can help those still in need.",
      "marks": []
     }
    ]
   },
   {
    "_type": "image",
    "_key": "kd",
    "src": "/news/pmg-helping-in-houston/IMG_0393-1024x683.jpg",
    "alt": "",
    "width": 1024,
    "height": 683
   },
   {
    "_type": "image",
    "_key": "ke",
    "src": "/news/pmg-helping-in-houston/IMG_0381-1024x683.jpg",
    "alt": "",
    "width": 1024,
    "height": 683
   },
   {
    "_type": "image",
    "_key": "kf",
    "src": "/news/pmg-helping-in-houston/IMG_0348-1024x683.jpg",
    "alt": "",
    "width": 1024,
    "height": 683
   },
   {
    "_type": "image",
    "_key": "kg",
    "src": "/news/pmg-helping-in-houston/IMG_0316-1024x683.jpg",
    "alt": "",
    "width": 1024,
    "height": 683
   },
   {
    "_type": "image",
    "_key": "kh",
    "src": "/news/pmg-helping-in-houston/IMG_0216-1024x683.jpg",
    "alt": "",
    "width": 1024,
    "height": 683
   },
   {
    "_type": "image",
    "_key": "ki",
    "src": "/news/pmg-helping-in-houston/IMG_0103-1024x683.jpg",
    "alt": "",
    "width": 1024,
    "height": 683
   },
   {
    "_type": "image",
    "_key": "kj",
    "src": "/news/pmg-helping-in-houston/IMG_0088-1024x683.jpg",
    "alt": "",
    "width": 1024,
    "height": 683
   }
  ]
 },
 {
  "slug": "thank-you-for-paying-it-forward",
  "title": "Thank You For Paying It Forward",
  "date": "2018-01-16",
  "body": [
   {
    "_type": "block",
    "_key": "kl",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "kk",
      "text": "To make a conscious effort in our communities to be a positive impact and convey our message of intentional service, PMG provided $10 cash to each PMG internal employee, partner center staff member, and provider to perform a random act of kindness on the same day. The cash was accompanied by a card branded to PMG and the partner hospital, pending hospital approval of the campaign.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "kn",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "km",
      "text": "With our partners help, over 225 random acts of kindness were done on December 6th to spread the word about our dedication to serving through our work together.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "kp",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "ko",
      "text": "Here are some ways our partners and team helped make someone else’s day a little brighter!",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "ks",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "kr",
      "text": "“I paid it forward to this cute little lady…bought her Subway dinner. She was so very excited!” – FTMC Pain Management Center (Norwalk, Ohio)",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "ku",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "kt",
      "text": "Staff members at the CHWC Pain Management Clinic in Bryan, Ohio…",
      "marks": [
       "strong"
      ]
     }
    ]
   },
   {
    "_type": "block",
    "_key": "kw",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "kv",
      "text": "– Donated to the Humane Society",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "ky",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "kx",
      "text": "– Donated towards purchasing movies for the troops",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k10",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "kz",
      "text": "– Left the cash in addition to what they would normally leave for a tip at a restaurant",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k12",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k11",
      "text": "– Purchased colored pencils for a child who needed them",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k14",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k13",
      "text": "Internal PMG employees…",
      "marks": [
       "strong"
      ]
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k16",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k15",
      "text": "– Added to the amount given and went to Walmart to contribute $100 to someone’s lay-away. “We randomly selected items that appeared to have young children toys, and the account we chose to cover came out to be $101.73!”",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k18",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k17",
      "text": "– Left money at a gas pump with the cards",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1a",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k19",
      "text": "– Donated to the Mid-Ohio Foodbank, only to find out later that December 6th was Double Donation Day for them. The amount donated was doubled by Big Lots and to purchase 160 meals.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1c",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1b",
      "text": "– Left a plate of cookies with the Pay It Forward card at a local coffee shop whose profits are all donated to charity.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1e",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1d",
      "text": "– Left the money on the breakfast table of hotel for the person working the breakfast",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1g",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1f",
      "text": "– Contributed the money to the Toys For Tots drive at Panera",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1i",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1h",
      "text": "– Two team members teamed up and donated $50 to a random Christmas lay-away at a local Walmart",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1k",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1j",
      "text": "– Paid for two cars behind at a McDonalds drive through",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1m",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1l",
      "text": "– Left the money as an added tip at a restaurant",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1o",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1n",
      "text": "– Used the money to help a man whose car broke down on the side of the road. Bought him the auto parts needed and helped him replace the pieces.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1q",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1p",
      "text": "– Contributed to a church food pantry",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1s",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1r",
      "text": "– Paid for the next person in line at Starbucks",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1u",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1t",
      "text": "Staff members at the Center for Pain Management at St. Vincent Charity Medical Center in Cleveland, Ohio…",
      "marks": [
       "strong"
      ]
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1w",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1v",
      "text": "– Gave the money to a mother and her three children at a Walmart Subway",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k1y",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1x",
      "text": "– Gave the money to a lady pumping gas. She said it should go to someone who needed it more, so I told her she could “pay it forward” again if she wanted!",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k20",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k1z",
      "text": "– Gave the money to a mother and her two children buying groceries at Walmart. I chipped in a bit more so their entire bill could be paid.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k22",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k21",
      "text": "– Gave the money to a father going into Save-A-Lot with his two daughters. The gentleman expressed his thanks and proceeded share that he was raised with the help of Ronald McDonald House because of a childhood illness.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k25",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k24",
      "text": "“On behalf of the Bellevue Hospital and Pain Management Group we would like to pay it forward to the people that matter most. For me that means the men and women who protect us every day, which is you. Please accept this from all of us at the Bellevue Pain Clinic and Merry Christmas.” – Bellevue Pain Management Center (Bellevue, Ohio)",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k27",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k26",
      "text": "Paulding Pain Management Center Staff in Paulding, Ohio…",
      "marks": [
       "strong"
      ]
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k29",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k28",
      "text": "– Donated to the Paulding County Hospital Foundation. The Foundation gives scholarships to area graduates who majored in healthcare and now give back to the county.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2b",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2a",
      "text": "Staff members at the Hocking Valley Pain Management Center in Logan, Ohio…",
      "marks": [
       "strong"
      ]
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2d",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2c",
      "text": "– $30 went to a little boy in our school district who is battling cancer. It went to a fund to help the family with expenses.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2f",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2e",
      "text": "– $30 went to a fund for teachers to buy supplies for the classroom.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2h",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2g",
      "text": "– $10 went to Kid Again, a group for kids with life threatening chronic illnesses – they take the kids on fun adventures.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2j",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2i",
      "text": "– $10 went to a person struggling to pay for Christmas for their family.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2l",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2k",
      "text": "– $10 went to buy a baby doll for a child whose family is having financial problems.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2n",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2m",
      "text": "Thank you for taking a few extra minutes out of your day to help someone else.",
      "marks": [
       "strong"
      ]
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2p",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2o",
      "text": "“Great Idea PMG!!!! Happy Holidays!”",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2r",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2q",
      "text": "“Great idea! I truly enjoyed blessing others with that money. Thank you so much!”",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2t",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2s",
      "text": "“Thank you again for arranging such an impactful organizational wide movement, and I look forward to hearing how others spent their $10!”",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2v",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2u",
      "text": "“Thank you for organizing this, what a wonderful idea!”",
      "marks": []
     }
    ]
   }
  ]
 },
 {
  "slug": "pain-management-group-receives-spirit-award-from-the-partnership-for-excellence",
  "title": "Pain Management Group Receives ‘Spirit Award’ From The Partnership For Excellence",
  "date": "2019-01-31",
  "body": [
   {
    "_type": "block",
    "_key": "k2x",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2w",
      "text": "Since Pain Management Group began in 2009, we have focused our organizational efforts on developing our expertise to be a resourceful, efficient, and valuable partner to hospitals and providers that want to provide accountable and safe pain treatment in their communities.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k2z",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k2y",
      "text": "As our mission continues to strengthen communities by partnering with hospitals to provide balanced pain management, we are embarking on an organizational journey to further focus our vision, refine our processes, and develop as a partner aligned to deliver excellence.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k34",
    "style": "normal",
    "markDefs": [
     {
      "_type": "link",
      "_key": "k31",
      "href": "http://baldrigefoundation.org/who-we-are/"
     }
    ],
    "children": [
     {
      "_type": "span",
      "_key": "k30",
      "text": "Over the last few months, PMG has been laying the groundwork to pursue the ",
      "marks": []
     },
     {
      "_type": "span",
      "_key": "k32",
      "text": "Baldrige Excellence Framework",
      "marks": [
       "k31"
      ]
     },
     {
      "_type": "span",
      "_key": "k33",
      "text": ". The Baldrige framework is an internationally renowned and established resource aimed at empowering organizations to reach their goals, improve results, and become more competitive in their industries.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k36",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k35",
      "text": "As we continue to grow and develop as an organization, our goal is to use the Baldrige framework as a guide to generate increased value to our hospital partners, team members, and providers, which will in turn impact our patients and ultimately, our communities.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k38",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k37",
      "text": "Over the coming years, we will spend considerable time refining our processes to meet the Baldrige criteria in the following key areas: Leadership, Strategy, Customers, Measurement, Analysis & Knowledge Management, Workforce, Operations, and Results.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k3d",
    "style": "normal",
    "markDefs": [
     {
      "_type": "link",
      "_key": "k3a",
      "href": "http://www.thepartnershipforexcellence.org/award_recognition_levels.html"
     }
    ],
    "children": [
     {
      "_type": "span",
      "_key": "k39",
      "text": "As we begin our Baldrige journey, we are excited to announce that PMG received the ",
      "marks": []
     },
     {
      "_type": "span",
      "_key": "k3b",
      "text": "Spirit Award",
      "marks": [
       "k3a"
      ]
     },
     {
      "_type": "span",
      "_key": "k3c",
      "text": " at The Partnership for Excellence: Quest for Success conference in Columbus, Ohio for completing our organizational profile.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k3f",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k3e",
      "text": "This profile is the first step in the Baldrige process that enables self-assessment to identify key information and performance gaps. As we strive to meet the criteria, we will participate in a cycle of self-evaluating, submitting applications, receiving and addressing feedback, and re-submitting for assessment.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k3h",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k3g",
      "text": "We believe that our developmental journey to focus on these key areas will positively impact our partners along the way and continually enhance the quality and performance we deliver within our partnerships.",
      "marks": []
     }
    ]
   }
  ]
 },
 {
  "slug": "pain-management-group-receives-the-partnership-for-excellence-silver-award-2022",
  "title": "Pain Management Group Receives The Partnership For Excellence Silver Award 2022",
  "date": "2022-08-29",
  "body": [
   {
    "_type": "block",
    "_key": "k3j",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k3i",
      "text": "The Partnership for Excellence (TPE) announced that Pain Management Group received the 2022 Silver Commitment to Excellence Award. The awards represent Ohio, Indiana, and West Virginia’s highest honor for performance excellence through innovation, results, and visionary leadership using the Baldrige Excellence Framework, and we are one of four organizations to receive an award this year.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k3l",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k3k",
      "text": "Since 2009, PMG has been partnering with hospitals and healthcare systems to establish and manage socially and medically responsible pain management programs. We have over 50 pain management center locations across 10 states, and we are continuing to grow. PMG has been working with TPE and utilizing the Baldrige performance excellence methodology since 2019 to engage in ongoing, comprehensive organizational assessment that helps us identify key strengths and prioritize opportunities for improvement. Through this performance excellence journey, we are better equipped to serve and support our partners with quantifiable outcomes and exemplary results.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k3n",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k3m",
      "text": "To receive this award, PMG was evaluated by an independent board of examiners in seven areas defined by the Baldrige Excellence Framework: leadership; strategy; customers; measurement, analysis, and knowledge management; workforce; operations; and results. The evaluation process included more than 1,000 hours of review, a site visit, and multiple layers of independent and board review.",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k3p",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k3o",
      "text": "“We are thrilled to receive this award that is truly a reflection of the hard work and commitment to service excellence that PMG is dedicated to deliver,” says PMG CEO John Bookmyer. PMG President, Mark Ozimek adds, “We are committed to continuing this journey of performance improvement as we work together with our hospital partners to improve the landscape of pain management in our communities today.”",
      "marks": []
     }
    ]
   },
   {
    "_type": "block",
    "_key": "k3r",
    "style": "normal",
    "markDefs": [],
    "children": [
     {
      "_type": "span",
      "_key": "k3q",
      "text": "To learn more about PMG and how we could help you safely and effectively care for patients suffering from pain in your community, please contact marketing@painmgmtgroup.com.",
      "marks": []
     }
    ]
   }
  ]
 }
];
