// Generated from inventory/partners.csv. Each old WordPress partner page 301s to its state page.

export const legacyPartnerPages: { slug: string; state: string }[] = [
  { slug: "acrmc-restorative-pain-care", state: "ohio" },
  { slug: "allegan-pain-management-center", state: "michigan" },
  { slug: "avita-pain-management-center-galion", state: "ohio" },
  { slug: "blanchard-valley-pain-management-center-findlay", state: "ohio" },
  { slug: "breckinridge-health-pain-management-center", state: "kentucky" },
  { slug: "clinton-pain-management-center", state: "ohio" },
  { slug: "columbus-regional", state: "north-carolina" },
  {
    slug: "community-hospitals-wellness-centers-pain-management-center",
    state: "ohio",
  },
  { slug: "crystal-clinic-pain-management-center", state: "ohio" },
  { slug: "decatur-county-memorial-pain-management-center", state: "indiana" },
  { slug: "edgerton-hospital-pain-spine-center", state: "wisconsin" },
  { slug: "edgewood-pain-management-center", state: "pennsylvania" },
  { slug: "ferrell-pain-management-center", state: "illinois" },
  { slug: "fisher-titus-pain-management-center-sandusky", state: "ohio" },
  { slug: "hancock-pain-management", state: "indiana" },
  { slug: "hardin-medical-center", state: "tennessee" },
  { slug: "harrison-memorial-pain-management", state: "kentucky" },
  { slug: "henry-county-pain-management-center", state: "ohio" },
  { slug: "houlton-regional-hospital", state: "maine" },
  { slug: "knox-center-for-pain-management", state: "ohio" },
  { slug: "madison-health-pain-management", state: "ohio" },
  { slug: "magruder-pain-management-center", state: "ohio" },
  { slug: "marshall-browning", state: "illinois" },
  { slug: "massac-hospital", state: "illinois" },
  { slug: "meadowview-interventional-pain-management", state: "kentucky" },
  { slug: "memorial-pain-clinic", state: "michigan" },
  { slug: "memorial-pain-solutions", state: "ohio" },
  { slug: "new-day-pain-management-center", state: "ohio" },
  { slug: "northern-maine-medical-center", state: "maine" },
  { slug: "ohio-county-pain-care", state: "kentucky" },
  { slug: "paulding-county-pain-management", state: "ohio" },
  { slug: "perry-county-memorial-hosplital", state: "indiana" },
  { slug: "putnam-county-hospital-pain-management-center", state: "indiana" },
  { slug: "rhea-pain-management-center", state: "tennessee" },
  { slug: "southeastern-pain-management", state: "ohio" },
  {
    slug: "spine-and-pain-program-at-mymichigan-medical-center-west-branch",
    state: "michigan",
  },
  { slug: "twin-lakes-pain-management-center", state: "kentucky" },
  { slug: "uh-samaritan-pain-clinic", state: "ohio" },
  { slug: "van-wert-county-pain-management-center", state: "ohio" },
  { slug: "wayne-health-pain-management", state: "ohio" },
];
