#!/usr/bin/env node
// Generates src/content/us-map.ts: simplified SVG outlines of the US states, pre-projected
// (Albers USA, 975 x 610) from the public-domain us-atlas package. The site renders them as
// static SVG, so the partner map needs no map library or tiles in the browser.
//
//   node scripts/generate-us-map.mjs

import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { feature } from "topojson-client";
import { presimplify, simplify } from "topojson-simplify";
import { geoPath } from "d3-geo";

const require = createRequire(import.meta.url);
const topology = JSON.parse(
  await readFile(require.resolve("us-atlas/states-albers-10m.json"), "utf8"),
);

// Drop detail smaller than about one pixel at full size.
const simplified = simplify(presimplify(topology), 1.2);
const states = feature(simplified, simplified.objects.states).features;

// Round coordinates to whole pixels to keep the file small.
const path = geoPath();
const round = (d) =>
  d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(Number(n))));

const slug = (name) => name.toLowerCase().replace(/[^a-z]+/g, "-");
const rows = states
  .map((s) => {
    const [[x0, y0], [x1, y1]] = path.bounds(s);
    return {
      slug: slug(s.properties.name),
      name: s.properties.name,
      d: round(path(s)),
      box: [x0, y0, x1 - x0, y1 - y0].map(Math.round),
    };
  })
  .sort((a, b) => a.slug.localeCompare(b.slug));

const out = `// Generated by scripts/generate-us-map.mjs from us-atlas (states-albers-10m). Do not edit.
// Albers USA projection, viewBox 0 0 975 610. box is [x, y, width, height].

export type StateShape = { slug: string; name: string; d: string; box: number[] };

export const usMapViewBox = "0 0 975 610";

export const stateShapes: StateShape[] = ${JSON.stringify(rows, null, 1)};
`;
await writeFile(new URL("../src/content/us-map.ts", import.meta.url), out);
console.log(`${rows.length} states, ${(out.length / 1024).toFixed(1)} KB`);
