// Writes docs/sample-figures.md: every sample figure shown on the review site, its value,
// what PMG must supply, and the pages that show it. Run after changing
// src/content/sample-figures.ts or the copy that uses it:
//
//   npm run sample-figures

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { sampleFigures } from "../src/content/sample-figures.ts";
import { pmgFigures, pmgSource } from "../src/content/pmg-figures.ts";

const root = new URL("..", import.meta.url);
const pagesDir = new URL("src/content/pages/", root);
const files = readdirSync(pagesDir).map((f) => ({
  name: f,
  text: readFileSync(join(pagesDir.pathname, f), "utf8"),
}));

const rows = Object.entries(sampleFigures).map(([key, f]) => {
  const where = files
    .filter((file) => file.text.includes(`{{SAMPLE: ${key}}}`))
    .map((file) => `\`src/content/pages/${file.name}\``)
    .join(", ");
  return `| \`${key}\` | ${f.value} | ${f.note} | ${where || "(dashboard tiles)"} |`;
});

const pmgRows = Object.entries(pmgFigures).map(([key, f]) => {
  const where = files
    .filter((file) => file.text.includes(`{{PMG: ${key}}}`))
    .map((file) => `\`src/content/pages/${file.name}\``)
    .join(", ");
  return `| \`${key}\` | ${f.value} | ${f.stated} | ${f.period} | ${where || "(dashboard tiles)"} |`;
});

writeFileSync(
  new URL("docs/sample-figures.md", root),
  `# Sample figures on the review site

**None of these numbers is a PMG fact.** They are illustrative values so the review site reads
realistically before PMG confirms the real figures. Every one is on PMG's confirmation list
(\`deliverables/PMG-items-to-confirm.md\`), renders with a \`data-sample\` attribute, and fails
\`npm run verify:urls -- <url> --launch\` and \`npm run audit:site -- <url> --launch\` until it
is replaced. To replace one, set its value in \`src/content/sample-figures.ts\` from PMG's
answer, then remove the sample and write the confirmed figure into the copy.

Generated by \`npm run sample-figures\` from \`src/content/sample-figures.ts\`.

| Key | Shown as | What PMG must supply | Used in |
| --- | --- | --- | --- |
${rows.join("\n")}

## Figures PMG has stated

These are PMG's own numbers, from ${pmgSource} (\`deliverables/PMG-Website-Onboarding-Homework-7.1.26.docx\`).
They render with a \`data-pmg\` attribute and do not fail the launch checks. PMG signs off the
wording and period on the confirmation list. Values live in \`src/content/pmg-figures.ts\`.

| Key | Shown as | What PMG wrote | Period | Used in |
| --- | --- | --- | --- | --- |
${pmgRows.join("\n")}
`,
);
console.log(`Wrote docs/sample-figures.md (${rows.length} figures)`);
