#!/usr/bin/env node
// Migrates the 36 Pain Education articles, verbatim, from the Phase 1 crawl.
//
//   node scripts/inventory/articles.mjs
//
// Writes:
//   src/content/legacy/articles.ts          each article body as Portable Text
//   inventory/source/pain-education/*.html  the original body HTML, for the verbatim test
//
// Slugs, titles, and categories come from inventory/education.csv. The live articles have
// no images and no publish dates, so neither is added.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  extractBody,
  htmlToPortableText,
  plainTextOfBlocks,
  plainTextOfHtml,
} from "./portable-text.mjs";

const ROOT = process.cwd();
const rows = (await readFile(join(ROOT, "inventory/education.csv"), "utf8"))
  .trim()
  .split("\n")
  .slice(1)
  .map((l) => {
    const cells = [...l.matchAll(/("(?:[^"]|"")*"|[^,]*)(?:,|$)/g)].map((m) =>
      m[1].replace(/^"|"$/g, "").replace(/""/g, '"'),
    );
    return { category: cells[0], title: cells[1], slug: cells[2] };
  });

await mkdir(join(ROOT, "inventory/source/pain-education"), { recursive: true });
const out = [];
for (const row of rows) {
  const html = await readFile(
    join(ROOT, "inventory/html", `pain-education__${row.slug}.html`),
    "utf8",
  );
  const body = extractBody(html);
  await writeFile(
    join(ROOT, "inventory/source/pain-education", `${row.slug}.html`),
    body,
  );
  const blocks = await htmlToPortableText(body);
  if (plainTextOfBlocks(blocks) !== plainTextOfHtml(body))
    throw new Error(`${row.slug}: migrated text differs from the live article`);
  out.push({ slug: row.slug, body: blocks });
}

const file = `// Generated by scripts/inventory/articles.mjs from the Phase 1 crawl. Do not edit by hand.
// The 36 Pain Education article bodies, verbatim, as Portable Text. Sanity holds the articles
// once imported (scripts/import-content.ts); until then the site reads this list.
// Titles, slugs, and categories live in ./education.ts.

export const legacyArticleBodies: { slug: string; body: unknown[] }[] = ${JSON.stringify(out, null, 1)};
`;
await writeFile(join(ROOT, "src/content/legacy/articles.ts"), file);
const embeds = out.flatMap((a) =>
  a.body.filter((b) => b._type.startsWith("viewmedica")),
);
console.log(
  `${out.length} articles, ${embeds.length} ViewMedica embeds, ${(file.length / 1024).toFixed(0)} KB`,
);
