#!/usr/bin/env node
// Migrates the 4 WordPress news posts, verbatim, from the Phase 1 crawl.
//
//   node scripts/inventory/news.mjs
//
// Writes:
//   src/content/legacy/news-posts.ts   each post body as Portable Text
//   public/news/<slug>/                post images that still exist on the live site
//   inventory/source/news/*.html       the original body HTML, for the verbatim test
//
// Wording is untouched (see portable-text.mjs). Any reference to an image that already
// returns 404 on the live site, whether an <img> or a link to the image file, is dropped;
// the linked text itself is kept.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  decode,
  extractBody,
  htmlToPortableText,
  plainTextOfBlocks,
  plainTextOfHtml,
} from "./portable-text.mjs";

const ROOT = process.cwd();
const posts = [
  "pmg-helping-in-houston",
  "thank-you-for-paying-it-forward",
  "pain-management-group-receives-spirit-award-from-the-partnership-for-excellence",
  "pain-management-group-receives-the-partnership-for-excellence-silver-award-2022",
];
const dates = Object.fromEntries(
  (await readFile(join(ROOT, "inventory/news.csv"), "utf8"))
    .trim()
    .split("\n")
    .slice(1)
    .map((l) => [l.match(/,\/([a-z0-9-]+)\/,/)[1], l.split(",")[0]]),
);

const status = new Map();
async function check(url) {
  const https = url.replace(/^http:/, "https:");
  if (!status.has(https)) {
    const res = await fetch(https);
    status.set(https, {
      ok: res.ok,
      code: res.status,
      body: res.ok ? Buffer.from(await res.arrayBuffer()) : null,
    });
  }
  return { url: https, ...status.get(https) };
}

const missing = [];
await mkdir(join(ROOT, "inventory/source/news"), { recursive: true });
const out = [];
for (const slug of posts) {
  const html = await readFile(
    join(ROOT, "inventory/html", `${slug}.html`),
    "utf8",
  );
  const title = decode(
    html.match(/<title>(.*?) &#8211; Pain Management Group<\/title>/)[1],
  );
  const bodyHtml = extractBody(html);
  await writeFile(
    join(ROOT, "inventory/source/news", `${slug}.html`),
    bodyHtml,
  );

  const body = await htmlToPortableText(bodyHtml, {
    onImage: async (tag, _key) => {
      const src = tag.match(/\ssrc="([^"]+)"/)?.[1];
      if (!src) return null;
      const res = await check(src);
      if (!res.ok) {
        missing.push(`${slug}: ${res.url} (${res.code} on the live site)`);
        return null;
      }
      const file = res.url.split("/").pop();
      await mkdir(join(ROOT, "public/news", slug), { recursive: true });
      await writeFile(join(ROOT, "public/news", slug, file), res.body);
      return {
        _type: "image",
        _key,
        src: `/news/${slug}/${file}`,
        alt: decode(tag.match(/\salt="([^"]*)"/)?.[1] ?? ""),
        width: Number(tag.match(/\swidth="(\d+)"/)?.[1] ?? 1024),
        height: Number(tag.match(/\sheight="(\d+)"/)?.[1] ?? 683),
      };
    },
  });

  // Links to image files that no longer exist: keep the text, drop the link.
  for (const block of body.filter((b) => b._type === "block")) {
    for (const def of [...block.markDefs]) {
      if (!/\.(jpe?g|png|gif|webp)$/i.test(def.href)) continue;
      if (!/painmgmtgroup\.com/.test(def.href)) continue;
      const res = await check(def.href);
      if (res.ok) continue;
      missing.push(
        `${slug}: link to ${res.url} (${res.code} on the live site)`,
      );
      block.markDefs = block.markDefs.filter((d) => d !== def);
      for (const span of block.children)
        span.marks = span.marks.filter((m) => m !== def._key);
    }
  }

  if (plainTextOfBlocks(body) !== plainTextOfHtml(bodyHtml))
    throw new Error(`${slug}: migrated text differs from the live post`);
  out.push({ slug, title, date: dates[slug], body });
}

const file = `// Generated by scripts/inventory/news.mjs from the Phase 1 crawl. Do not edit by hand.
// The 4 WordPress news posts, verbatim, as Portable Text. Sanity holds news once imported
// (scripts/import-content.ts); until then the site reads this list.
// References to images already missing on the live site were dropped:
${[...new Set(missing)].map((m) => `//   ${m}`).join("\n")}

export type LegacyImage = {
  _type: "image";
  _key: string;
  src: string;
  alt: string;
  width: number;
  height: number;
};
export type LegacyBlock = {
  _type: "block";
  _key: string;
  style: string;
  listItem?: string;
  level?: number;
  markDefs: { _type: "link"; _key: string; href: string }[];
  children: { _type: "span"; _key: string; text: string; marks: string[] }[];
};
export type LegacyNewsPost = {
  slug: string;
  title: string;
  date: string;
  body: (LegacyBlock | LegacyImage)[];
};

export const legacyNewsBodies: LegacyNewsPost[] = ${JSON.stringify(out, null, 1)};
`;
await writeFile(join(ROOT, "src/content/legacy/news-posts.ts"), file);
console.log(out.map((p) => `${p.slug}: ${p.body.length} blocks`).join("\n"));
console.log([...new Set(missing)].join("\n"));
